version: '3'

services:
  dev:
    container_name: dev-container-dev-1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - vscode-extensions:/home/vscode/.vscode-server/extensions
      - workspaces:/home/vscode/workspaces
      - bash-history:/home/vscode/.bash_history_dir
      - git-config:/home/vscode/.gitconfig_dir
      - m2-repo:/home/vscode/.m2
      - sophora-repo:/home/vscode/sophora-repo
      - ssh:/home/vscode/.ssh
      - restic-repos:/home/vscode/restic-repos
      - containerrunner:/home/vscode/.containerrunner
      - go-fuzz-cache:/home/vscode/.cache/go-build/fuzz
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-container
    command: /home/vscode/containerrunner -config /home/vscode/.containerrunner/config.yaml

  pg:
    container_name: dev-container-pg-1
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - dev-container

volumes:
  vscode-extensions:
  workspaces:
  bash-history:
  git-config:
  m2-repo:
  sophora-repo:
  ssh:
  restic-repos:
  containerrunner:
  go-fuzz-cache:
  pg:

networks:
  dev-container:
