version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - vscode-extensions:/home/vscode/.vscode-server/extensions
      - workspaces:/home/vscode/workspaces
      - bash-history:/home/vscode/.bash_history_dir
      - git-config:/home/vscode/.gitconfig_dir
      - m2-repo:/home/vscode/.m2
      - sophora-repo:/home/vscode/sophora-repo
      - ssh:/home/vscode/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-container
    command: /bin/sh -c "while sleep 1000; do :; done"

  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - dev-container

volumes:
  vscode-extensions:
  workspaces:
  bash-history:
  git-config:
  m2-repo:
  sophora-repo:
  ssh:
  pg:

networks:
  dev-container:
